### ISSUE TITLE
Wrong timestamp for posts

### ISSUE THREAD

**Issue by kennyevo** [rb-de0/yubatake#118]
First of all: it's a very nice blog template!

I have the simple issue that my created_at and modified_at timestamps are off by one hour in the DB.
now() shows the correct time, mysql uses SYSTEM, and my server is in my timezone (CET).

Do you have any idea what could cause this? Is it a Fluent issue?

Thanks!

**Comment by rb-de0** [comment]
Thanks!

There are no special processes relating timezone in `yubatake`.
I think that the cause is that mysql library insert datetime by converting to GMT.

see: https://github.com/vapor/mysql/blob/3.1.0/Sources/MySQL/Connection/MySQLData.swift#L616
